version: '2'

services:

  # nginx:
  #   build:
  #     context: .
  #     dockerfile: .docker/nginx.dockerfile
  #   depends_on:
  #     - admin
  #   environment:
  #     - VIRTUAL_HOST=prototype-admin.iammoon.xyz
  #   ports:
  #     - "9998:8080"
  #   networks:
  #     - app-network

  admin:
    container_name: admin_web_site
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    #volumes:
    #  - .:/app
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      #- PORT=3000
      - INSTANCE=admin
      - VIRTUAL_HOST=prototype-admin.iammoon.xyz
    networks:
      - app-network


networks:
  app-network:
    external:
      name: nginx-proxy